### ISSUE TITLE
Editor component for cell ?

### ISSUE THREAD

**Issue by revskill10** [energydrink9/functional-data-grid#11]
So we have renderer, filter, comparator, what's missing here is the editor.
Do you have plan to implement it ?

**Comment by energydrink9** [comment]
Hi @revskill10 

You don't really need the editor, because you can return any JSX, containing textboxes, dropdowns, buttons etcetera in the renderer of the columns. You can switch between the view / edit mode at the hover or at the click of an edit button, by saving an edit flag per each row.
Through the change event handlers of the controls you can update the global state and update the data you've passed to the grid.
