### ISSUE TITLE
Immutable dependency? Why?

### ISSUE THREAD

**Issue by FredyC** [energydrink9/functional-data-grid#9]
Personally, I stopped using Immutable a long time ago as it's just too bloated and cumbersome. I don't understand why would you put it as a requirement for this neat looking data grid and not even mention it anywhere except a first example :) I would recommend something really functional like Ramda instead. And even if you really need it, you should take care of wrapping input data into an appropriate Imm structure by yourself. The primitive example from readme blew up into my face without using Immutable.

**Comment by energydrink9** [comment]
Hi FredyC

I've used Immutable because it's a functional library for collections and I needed something to do lists and maps manipulations. Plain JS arrays are mutable and it becomes quite difficult to know if they've been modified by the user. Anyway I'll look at Ramda... maybe it could be a better fit?

Actually, I understand the fact that the library API should accept plain JS arrays... We could take them and convert them inside the data grid component... how about that?

**Comment by FredyC** [comment]
Even a good old Lodash can do manipulations over collections and it has a functional variant as well. If a user actually tries to mutate data supplied to the component, it's kinda his fault in getting weird behavior. I don't see a point in bloating the library code in anticipation that every user is dumb to do such a thing.

> Actually, I understand the fact that the library API should accept plain JS arrays... We could take them and convert them inside the data grid component... how about that?

Yea, I've suggested that. I believe that Immutable even has some method for detecting if the passed value is one of its own, so if you do that, you can keep this requirement out of userland. But still, I would avoid using that lib at all.

**Comment by energydrink9** [comment]
> Even a good old Lodash can do manipulations over collections and it has a functional variant as well.

Lodash could be another good alternative to Immutable. I have to think a bit about it...

> If a user actually tries to mutate data supplied to the component, it's kinda his fault in getting weird behavior. I don't see a point in bloating the library code in anticipation that every user is dumb to do such a thing.

One of the use cases of the library is exactly to react to modifications of the input data due to the interaction of the user with the data grid, for example through buttons and other controls rendered in the columns.

> > Actually, I understand the fact that the library API should accept plain JS arrays... We could take them and convert them inside the data grid component... how about that?
> 
> Yea, I've suggested that. I believe that Immutable even has some method for detecting if the passed value is one of its own, so if you do that, you can keep this requirement out of userland. But still, I would avoid using that lib at all.

Okay, I'll modify the API to accept plain JS arrays.
Regarding the collections library, I'll take some time. Maybe someone else could contribute with other ideas...
